import test from 'node:test';
import assert from 'node:assert/strict';
import {safeToHomeFreeCell,autoHomeFreeCell,moveFreeCell,undoFreeCell,restoreFreeCell,isFreeCellWon,createFreeCellGame} from '../src/games/freecell.js';
const card=(s,r)=>s*13+r-1;
const foundations=counts=>counts.map((n,s)=>Array.from({length:n},(_,i)=>card(s,i+1)));
function board(cols=[],cells=[null,null,null,null],homes=foundations([0,0,0,0])){const used=[...cols.flat(),...cells.filter(c=>c!==null),...homes.flat()];const columns=Array.from({length:8},(_,i)=>cols[i]?.slice()||[]);columns[7].unshift(...Array.from({length:52},(_,i)=>i).filter(c=>!used.includes(c)));return {columns,freecells:cells.slice(),foundations:homes,moves:0,history:[]};}
const col=index=>({type:'column',index});
test('A and 2 are safe only when their own foundation accepts them',()=>{const s=board();assert.equal(safeToHomeFreeCell(s,card(0,1)),true);assert.equal(safeToHomeFreeCell(s,card(0,2)),false);s.foundations[0]=[card(0,1)];assert.equal(safeToHomeFreeCell(s,card(0,2)),true);});
test('higher cards wait for both opposite-colored foundations one rank below',()=>{const s=board([],undefined,foundations([3,2,3,0]));assert.equal(safeToHomeFreeCell(s,card(0,4)),false);s.foundations[1].push(card(1,3));assert.equal(safeToHomeFreeCell(s,card(0,4)),true);assert.equal(safeToHomeFreeCell(s,card(3,4)),false);});
test('one click repeatedly homes safe exposed cards and undoes the whole batch',()=>{const s=board([[card(0,2),card(0,1)],[card(1,1)]]);const before=structuredClone(s),next=autoHomeFreeCell(s);assert.deepEqual(next.foundations[0],[card(0,1),card(0,2)]);assert.deepEqual(next.foundations[1],[card(1,1)]);assert.equal(next.moves,1);assert.equal(next.history.length,1);assert.deepEqual(undoFreeCell(next),s);assert.deepEqual(s,before);});
test('unsafe card stays on tableau even when manually eligible for foundation',()=>{const s=board([[card(0,4)]],undefined,foundations([3,2,3,0]));const next=autoHomeFreeCell(s);assert.ok(next.columns[0].includes(card(0,4)));});
test('safe cards in free cells are included and no-op creates no history or move',()=>{const s=board([], [card(2,1),null,null,null]);const next=autoHomeFreeCell(s);assert.equal(next.freecells[0],null);assert.equal(next.foundations[2][0],card(2,1));const empty=board([[card(0,5)],[card(1,6)]]);assert.equal(autoHomeFreeCell(empty),empty);});
test('enabled auto-home joins the user move in one undo transaction',()=>{const s={...board([[card(0,1),card(1,5)],[card(0,6)]]),autoHome:true};const n=moveFreeCell(s,col(0),col(1));assert.equal(n.moves,1);assert.deepEqual(n.foundations[0],[card(0,1)]);assert.equal(n.history.length,1);assert.deepEqual(undoFreeCell(n),s);});
test('disabled auto-home leaves newly exposed aces untouched',()=>{const s={...board([[card(0,1),card(1,5)],[card(0,6)]]),autoHome:false};const n=moveFreeCell(s,col(0),col(1));assert.equal(n.foundations[0].length,0);assert.equal(n.columns[0].at(-1),card(0,1));});
test('old saves default off; new preference and grouped undo survive JSON roundtrip',()=>{const old=board([[card(0,1),card(1,5)],[card(0,6)]]);assert.equal(!!restoreFreeCell(old).autoHome,false);const s={...old,autoHome:true},n=moveFreeCell(s,col(0),col(1));assert.deepEqual(undoFreeCell(restoreFreeCell(JSON.parse(JSON.stringify(n)))),s);});
test('a finishable position homes all remaining cards',()=>{const s=board([[card(0,13)],[card(1,13)],[card(2,13)],[card(3,13)]],undefined,foundations([12,12,12,12]));assert.equal(isFreeCellWon(autoHomeFreeCell(s)),true);});
test('UI auto-home settles once, has persistent toggle, and cleans event listener',()=>{const listeners=new Map();let finished=0,clears=0,saves=0;const root={innerHTML:'',addEventListener:(k,f)=>listeners.set(k,f),removeEventListener:k=>listeners.delete(k)};const doc={getElementById:()=>true};const s=board([[card(0,13)],[card(1,13)],[card(2,13)],[card(3,13)]],undefined,foundations([12,12,12,12]));const game=createFreeCellGame({root,document:doc,isPaused:()=>false,isActive:()=>true,save:()=>saves++,clear:()=>clears++,finish:()=>finished++,speak(){},toast(){},setScore(){}},s);const click=action=>listeners.get('click')({target:{closest:selector=>selector==='[data-action]'?{dataset:{action}}:null}});click('toggle-auto');assert.equal(game.getState().autoHome,true);assert.match(root.innerHTML,/随步归档：开/);click('auto-home');assert.equal(finished,1);assert.equal(clears,1);click('auto-home');game.save();assert.equal(finished,1);const count=saves;game.destroy();game.save();assert.equal(saves,count);assert.equal(listeners.size,0);});
